Gemini API Key - 秘密鍵をここに設定してください

GEMINI_API_KEY = "AIzaSyCebpuZmUui7d01KR7aJIVfg-YLhqu3Mec"

認証ユーザー情報 (パスワードは平文で記述されています)

[auth_users.admin]
name = "管理者"
password = "admin_pass" # 平文パスワード

[auth_users.user1]
name = "ユーザー１"
password = "admin_pass" # 平文パスワード