Gemini API Key - 秘密鍵をここに設定してください

GEMINI_API_KEY = "AIzaSyCebpuZmUui7d01KR7aJIVfg-YLhqu3Mec"

認証ユーザー情報

パスワードは必ずSHA256でハッシュ化して保存してください。

例: admin_pass のSHA256ハッシュ値

ADMIN_PASS_HASH = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8831f65df05204c30"

[auth_users.admin]
name = "管理者"
password_hash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8831f65df05204c30"

[auth_users.user1]
name = "ユーザー１"
password_hash = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8831f65df05204c30"